### ISSUE TITLE
数据集问题，

### ISSUE THREAD

**Issue by Alex-lcy** [wurenkai/H-vmunet#10]
在进行数据集处理的时候，我总是出问题，我是新手小白，我想问一下能不能从您这得到已经处理好的数据集。如何能得到您的帮助我将要十分感谢。

**Comment by Alex-lcy** [comment]
您好作者，在您的帮助下，我在ISIC2017，已经能跑通，但我在下载完另外两个数据集的，他们的文件后缀CVC-ClinicDB.tif和Task09_Spleen的后缀.nii.zg 是否需要转换为png等格式，这个Task09_Spleen在官网下载是3D的如何进行的切片。                                         如果直接运行就会报错：:

Traceback (most recent call last):
  File "lcydata.py", line 8, in <module>
    img = nib.load(nii_path)
  File "/opt/conda/envs/tool/lib/python3.7/site-packages/nibabel/loadsave.py", line 92, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '/mnt/workspace/H-vmunet/data/Task09_Spleen/labesTr/spleen_6.nii.gz'

**Comment by pinzic** [comment]
不好意思啊，这是我准备跑通的第一个复现论文，所以想请问能否指导一下下载好数据集之后，该如何运行Prepare_ISIC2017.py文件呢？数据集的目录该设置在哪里呢？或者给一下已经处理好的数据集，十分感谢作者！！

**Comment by kongweitao190** [comment]
前面两个数据集都可以跑通，可以具体说一下spleen整个数据集要怎么处理吗？
